// user actions
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

// map actions
export const GET_POSITION_SUCCESS = 'GET_POSITION_SUCCESS';
export const SET_LAST_CLICK_POSITION = 'SET_LAST_CLICK_POSITION';

// target actions
export const CREATE_TARGET_SUCCESS = 'CREATE_TARGET_SUCCESS';
export const GET_TARGETS_SUCCESS = 'GET_TARGETS_SUCCESS';
