// app actions
export const INCREASE_FETCHING_INDICATOR = 'INCREASE_FETCHING_INDICATOR';
export const DECREASE_FETCHING_INDICATOR = 'DECREASE_FETCHING_INDICATOR';
export const FETCHING_ERROR = 'FETCHING_ERROR';
export const CLEAR_FETCHING_ERROR = 'CLEAR_FETCHING_ERROR';

// user actions
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

// map actions
export const GET_POSITION_SUCCESS = 'GET_POSITION_SUCCESS';
export const SET_LAST_CLICK_POSITION = 'SET_LAST_CLICK_POSITION';

// target actions
export const CREATE_TARGET_SUCCESS = 'CREATE_TARGET_SUCCESS';
export const FETCH_TARGETS_SUCCESS = 'FETCH_TARGETS_SUCCESS';
